swagger: "2.0"
info:
  description: EndPoint Configuration file for Swagger.
  version: "0.1.0"
  title: Relop Todo WebApp
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /login/{hashid}:
    get:
      operationId: tasker.auth
      tags:
        - Login
      summary: Login to your relop account
      description: This endpoint provides all user information when right hash is provided as parameter. 
      parameters:
        - name: hashid
          in: path
          description: identification hash of user 
          type: string
          required: True
      responses:
        200:
          description: Authenticated Successfully
          schema:
            properties:
              hashid:
                type: string
                description: Identification hash of user
              username:
                type: string
                description: username of the user in the database
              fullname:
                type: string
                description: Name of the user

  /login/:
    post:
      operationId: tasker.addaccount
      tags:
        - Login
      summary: Create a new account
      description: This endpoint is used for creating new relop account
      parameters:
        - name: account
          in: body
          description: account to create
          required: True
          schema:
            type: object
            properties:
              hashid:
                type: string
                description: identification hash of user
              username:
                type: string
                description: username for given account
              fullname:
                type: string
                description: provided fullname of account holder
      responses:
        201:
          description: Successfully created
          schema:
            properties:
              hashid:
                type: string
                description: Identification hash of user
              username:
                type: string
                description: username of givem account
              fullname:
                type: string
                description: fullname of user
              timestamp:
                type: string
                description: creation time of account

  /tasker/{hashid}:
    get:
      operationId: tasker.read
      tags:
        - Tasker
      summary: Read all task by a single account
      description: Read all task by a single account
      parameters:
        - name: hashid
          in: path
          description: Identification hash of user
          type: string
          required: True
        - name: status
          in: query
          type: string
          description: return Items for specific completed status
          required: false
      responses:
        200:
          description: Successfully read person from people data operation
          schema:
            type: object
            properties:
              taskid:
                type: string
                description: Identification hash of user
              task:
                type: string
                description: task that is to be added to this account
              completed:
                type: string
                description: status of task
              timestamp:
                type: string
                description: timestamp of creation/updation

    post:
      operationId: tasker.create
      tags:
        - Tasker
      summary: Create a Task
      description: Create a new Task
      parameters:
        - name: hashid
          in: path
          description: identification hash of user
          type: string
          required: True
        - name: todo
          in: body
          description: task to create
          required: True
          schema:
            type: object
            properties:
              task:
                type: string
                description: topic of task to create
              completed:
                type: boolean
                description: status of task
      responses:
        201:
          description: Successfully created
          schema:
            properties:
              task_id:
                type: string
                description: Id of the task
              task:
                type: string
                description: content of the task
              completed:
                type: boolean
                description: status of task
              timestamp:
                type: string
                description: Creation time of task

    put:
      operationId: tasker.update
      tags:
        - Tasker
      summary: update a Task
      description: update an existing Task
      parameters:
        - name: hashid
          in: path
          description: Identification hash of user
          type: string
          required: True
        - name: todo
          in: body
          description: body of task to update including task_if
          required: True
          schema:
            type: object
            properties:
              task_id:
                type: integer
                description: id of task to update
              task:
                type: string
                description: updated task description
              completed:
                type: boolean
                description: status of task
      responses:
        201:
          description: Successfully created
          schema:
            properties:
              task_id:
                type: string
                description: Id of the task
              task:
                type: string
                description: content of the task
              completed:
                type: boolean
                description: status of task
              timestamp:
                type: string
                description: updated timestamp

  /tasker/{hashid}/{taskid}:
    delete:
      operationId: tasker.delete
      tags:
        - Tasker
      summary: Delete a task based on hashid of user and taskid
      description: Delete a task
      parameters:
        - name: hashid
          in: path
          type: string
          description: Identification hash of user
          required: true
        - name: taskid
          in: path
          type: integer
          description: Id of the task to delete
          required: true
      responses:
        200:
          description: Successfully deleted a task
